---

- name: "Speedtest Tracker"
  hosts: localhost
  connection: local
  vars:
    speedtest_tracker_docker_image: "henrywhitaker3/speedtest-tracker"
  tasks:
    - name: Deploy speedtest container
      docker_container:
        name: "speedtest"
        hostname: "speedtest"
        image: "{{ speedtest_tracker_docker_image }}"
        env:
          TZ: 'America/Toronto'
          OOKLA_EULA_GDPR: 'true'
        labels:
          traefik.enable: "true"
          traefik.docker.network: "app_network"
          traefik.http.routers.speedtest.rule: "Host(`speedtest.{{ do_domain }}`)"
          traefik.http.routers.speedtest.entrypoints: "https"
          traefik.http.routers.speedtest.tls: "true"
          traefik.http.routers.speedtest.tls.certresolver: "le"
          traefik.http.services.speedtest.loadbalancer.server.port: "80"
        networks:
          - name: "app_network"
        restart_policy: always
        memory: '500M'
        state: started
        pull: false
        network_mode: "default"
        container_default_behavior: "compatibility"
      # added retry to tasks dependant on external services
      register: result
      retries: 5
      delay: 3
      until: result is succeeded
      when:
        - not ansible_check_mode
